### ISSUE TITLE
Failing to setup dev environment (it's all my fault)

### ISSUE THREAD

**Issue by MasinAD** [cfengine/cf-remote#89]
I already fail at setting up a dev environment! :-D

```
(.venv) masin.wiedner@wmde-103180:~/Projekte/cf-remote$ LANG=C pip install -v --editable .
Using pip 24.0 from /var/home/masin.wiedner/Projekte/cf-remote/.venv/lib64/python3.12/site-packages/pip (python 3.12)
Obtaining file:///var/home/masin.wiedner/Projekte/cf-remote
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-70.1.0-py3-none-any.whl.metadata (6.0 kB)
  Using cached setuptools-70.1.0-py3-none-any.whl (882 kB)
  Installing collected packages: setuptools
  Successfully installed setuptools-70.1.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  fatal: No names found, cannot describe anything.
  Traceback (most recent call last):
    File "/var/home/masin.wiedner/Projekte/cf-remote/.venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/var/home/masin.wiedner/Projekte/cf-remote/.venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/home/masin.wiedner/Projekte/cf-remote/.venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-xbuj4zhn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-xbuj4zhn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-xbuj4zhn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-xbuj4zhn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-xbuj4zhn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 20, in <module>
  AssertionError
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /var/home/masin.wiedner/Projekte/cf-remote/.venv/bin/python /var/home/masin.wiedner/Projekte/cf-remote/.venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_editable /tmp/tmph4e4d06h
  cwd: /var/home/masin.wiedner/Projekte/cf-remote
  Getting requirements to build editable ... error
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

What did I do?
1. I cloned the forked repository: `git clone git@github.com:MasinAD/cf-remote.git`
2. I changed into the directory `cf-remote/` and created a virtual environment: `python -m venv .venv`
3. `. .venv/bin/activate`, of course
4. But then, `pip install -e .` throws this error. 
5. I even installed the single requirement from requirements.txt manually: `pip install apache-libcloud==3.3.1`
6. I then tried installing `cf-remote` from PyPI to get the venv setup for everything, then uninstall it again: `pip install cf-remote && pip uninstall cf-remote`
7. But `pip install -v -e .` always throws that error.

I tried looking at the file referenced in the line `full command: /var/home/masin.wiedner/Projekte/cf-remote/.venv/bin/python /var/home/masin.wiedner/Projekte/cf-remote/.venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_editable /tmp/tmph4e4d06h` but either it doesn't get created and is missing (I ^Z'ed at "Running command Getting requirements to build editable") or I don't get the correct moment of its extistence.

Any hint what's going on?

**Comment by MasinAD** [comment]
@olehermanse Thanks for the hint. That almost worked. My mistake was to fork the repo and to try setting up the dev environment based on my fork. But forks don't contain the branches and the tags as I just found out. After `git config remote.origin.url https://github.com/cfengine/cf-remote.git` your `git fetch --all --tags` worked and `pip install -e .` could finish.
